# Generated by Django 5.2.17 on 2026-08-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
