# Generated by Django 5.2.17 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_google_connected_at_user_google_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_teacher_approved",
            field=models.BooleanField(
                default=False,
                help_text="Allows teacher users to access the school teacher dashboard after admin review.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="teacher_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
