# Generated by Django 5.2.17 on 2026-08-27 20:28

import accounts.models
from django.db import migrations, models


def move_legacy_admin_role_to_student(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="ADMIN").update(role="STUDENT")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacher_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.TeacherManager()),
            ],
        ),
        migrations.RunPython(move_legacy_admin_role_to_student, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', help_text='App role for teacher/student flows. Django admin access is controlled by superuser status.', max_length=20),
        ),
    ]
