# Generated by Django 5.2.17 on 2026-08-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=100)),
                ('is_pastor', models.BooleanField()),
                ('has_studied_bri', models.BooleanField()),
                ('facebook_link', models.URLField(max_length=500)),
                ('region', models.CharField(choices=[('northern', 'เหนือ'), ('central', 'กลาง'), ('northeastern', 'อีสาน'), ('southern', 'ใต้')], max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sub_district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('church', models.CharField(max_length=255)),
                ('serving_position', models.CharField(blank=True, max_length=255)),
                ('mentor_name', models.CharField(max_length=255)),
                ('believer_years', models.PositiveIntegerField()),
                ('goal', models.TextField()),
                ('vision_calling', models.TextField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='school.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
