# Generated by Django 5.2.17 on 2026-08-10 10:50

import django.db.models.deletion
from django.db import migrations, models


def populate_student_ids(apps, schema_editor):
    Student = apps.get_model("school", "Student")

    max_number = 0
    for value in Student.objects.exclude(student_id__isnull=True).values_list("student_id", flat=True):
        suffix = value.removeprefix("bri-")
        if suffix.isdigit():
            max_number = max(max_number, int(suffix))

    next_number = max_number + 1
    for student in Student.objects.order_by("id").iterator():
        if student.student_id:
            continue
        student.student_id = f"bri-{next_number:04d}"
        student.save(update_fields=["student_id"])
        next_number += 1


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rebuild_school_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration',
        ),
        migrations.AddField(
            model_name='person',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('in_progress', 'ดำเนินการ'), ('passed', 'ผ่าน'), ('failed', 'ไม่ผ่าน')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(populate_student_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='person_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='school.person'),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
