# Generated by Django 5.2.17 on 2026-08-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_student_is_paid_student_payment_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
