# Generated by Django 5.2.17 on 2026-08-12 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_person_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='line_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='line_display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='line_picture_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='person',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('line_user_id', ''), _negated=True), fields=('line_user_id',), name='uniq_person_line_user_id_when_present'),
        ),
    ]
