# Generated by Codex on 2026-09-08

from django.db import migrations, models


def backfill_passed_admission_type(apps, schema_editor):
    Person = apps.get_model("school", "Person")
    Person.objects.filter(status="passed", admission_type="").update(
        admission_type="interview"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_person_line_connected_at_person_line_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="admission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interview", "ผ่านสัมภาษณ์"),
                    ("online", "ผ่านแบบออนไลน์"),
                ],
                default="",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            backfill_passed_admission_type,
            migrations.RunPython.noop,
        ),
    ]
