# Generated by Django 5.2.17 on 2026-09-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_person_admission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='interview_details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='interview_notification_state',
            field=models.CharField(blank=True, choices=[('pending', 'รอส่ง'), ('sent', 'LINE รับข้อความแล้ว'), ('failed', 'ส่งไม่สำเร็จ')], max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='interview_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
