# Generated by Django 5.2.17 on 2026-09-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_appointment_slots'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='uniq_person_line_id_when_present',
        ),
        migrations.RemoveField(
            model_name='person',
            name='line_id',
        ),
    ]
